# NumPy

- Permite operações matemáticas 
- Mais veloz que listas pois permitem apenas um tipo de dados

In [ ]:
lista = [1, 4, 9, 10, 11]

In [ ]:
import numpy as np

In [ ]:
l_array = np.array(lista)

In [ ]:
print(lista)
type(lista)

[1, 4, 9, 10, 11]


list

In [ ]:
print(l_array)
type(l_array)

[ 1  4  9 10 11]


numpy.ndarray

In [ ]:
lista2 = [[5, 1.75], [6, 1.6], [9, 1.2], [3, 1.5], [7, 1.7]]

In [ ]:
print(lista2)
l2_array = np.array(lista2)
print(l2_array)
type(l2_array)

[[5, 1.75], [6, 1.6], [9, 1.2], [3, 1.5], [7, 1.7]]
[[5.   1.75]
 [6.   1.6 ]
 [9.   1.2 ]
 [3.   1.5 ]
 [7.   1.7 ]]


numpy.ndarray

In [ ]:
l2_array[:,1]

array([1.75, 1.6 , 1.2 , 1.5 , 1.7 ])

In [ ]:
l2_array[1,:]

array([6. , 1.6])

In [ ]:
l2_array[0:2,:]

array([[5.  , 1.75],
       [6.  , 1.6 ]])

In [ ]:
l2_array[:,0]

array([5., 6., 9., 3., 7.])

In [ ]:
l_array

array([ 1,  4,  9, 10, 11])

In [ ]:
l_array * 2

array([ 2,  8, 18, 20, 22])

In [ ]:
l2_array

array([[5.  , 1.75],
       [6.  , 1.6 ],
       [9.  , 1.2 ],
       [3.  , 1.5 ],
       [7.  , 1.7 ]])

In [ ]:
l2_array * 2

array([[10. ,  3.5],
       [12. ,  3.2],
       [18. ,  2.4],
       [ 6. ,  3. ],
       [14. ,  3.4]])

In [ ]:
l_array

array([ 1,  4,  9, 10, 11])

In [ ]:
np.mean(l_array)

7.0

In [ ]:
np.median(l_array)

9.0

In [ ]:
l2_array.shape

(5, 2)

In [ ]:
l3_array = np.array([1, 2, 3, 4, "5"])

In [ ]:
l3_array

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [ ]:
l_array

array([ 1,  4,  9, 10, 11])

In [ ]:
l_array > 9

array([False, False, False,  True,  True])

In [ ]:
l_array[l_array > 9]

array([10, 11])

In [ ]:
l_array + l_array

array([ 2,  8, 18, 20, 22])

In [ ]:
lista + lista

[1, 4, 9, 10, 11, 1, 4, 9, 10, 11]

# Exercício 1
- Dados as listas abaixo:

In [ ]:
altura = [1.73, 1.68, 1.71, 1.89, 1.79]

In [ ]:
peso = [65.4, 59.2, 63.6, 88.4, 68.7]

- Importe numpy as np
- crie dois numpy arrays com a altura e o peso de 5 pessoas baseados na lista acima
- calcule o indice de massa corporal de cada uma das 5 pessoas e armazeno em um array chamado imc (imc = peso / altura**2)
- imprima o array imc
- selecione do array imc apenas as pessoas que estiverem com icm acima de 23 e armazene no array sobrepeso
- imprima o array sobrepeso

# Exercício 2
- Dadas as listas abaixo:

In [ ]:
year = [1950, 1970, 1990, 2010]
pop = [2.519, 3.692, 5.263, 6.972]

- Importe matplotlib.pyplot as plt
- plote um gráfico em linha com o método plt.plot(x,y)
- plotte um scatter plot com o método plt.scatter(x,y)
- use os métodos plt.xlabel(), plt.ylabel() e plt.title() para descrever os gráficos
