# Dicionários

In [ ]:
pop = [30.55, 2.77, 39.21]
countries = ["afghanistan", "albania", "algeria"]


In [ ]:
pop[0]

30.55

In [ ]:
countries[0]

'afghanistan'

In [ ]:
pop[countries.index("albania")]

2.77

In [ ]:
world = {"afghanistan":30.55, "albania":2.77, "algeria":39.21}

In [ ]:
world["albania"]

2.77

In [ ]:
world = {"afghanistan":30.55, "albania":2.77, "algeria":39.21, "albania":2.81}

In [ ]:
world

{'afghanistan': 30.55, 'albania': 2.81, 'algeria': 39.21}

In [ ]:
world["sealand"] = 0.000027

In [ ]:
world

{'afghanistan': 30.55, 'albania': 2.81, 'algeria': 39.21, 'sealand': 2.7e-05}

In [ ]:
"sealand" in world

True

In [ ]:
world["sealand"]

2.7e-05

In [ ]:
world["sealand"] = 0.000028

In [ ]:
world

{'afghanistan': 30.55, 'albania': 2.81, 'algeria': 39.21, 'sealand': 2.8e-05}

In [ ]:
world["sealand"]

2.8e-05

In [ ]:
del(world["sealand"])

In [ ]:
world

{'afghanistan': 30.55, 'albania': 2.81, 'algeria': 39.21}

# Listas

- select, update e remove [ ]
- indexado por uma sequencia de números
- coleção de valores
- ordem importa
- subconjuntos podem ser selecionados

# Dicionários

- select, update e remove [ ]
- indexado por chaves únicas
- tabela de pesquisa com chaves únicas

# Pandas

Como manipular tabelas em Python? 2D NumPy Arrays? Mesmo tipo de dados?

Em tabelas as linhas são observações e cada coluna uma variável ou propriedade observada

Tipos de dados diferentes!

O Pandas é:
- Uma ferramenta de alto nível para manipulação de dados
- Construída sobre o NumPy
- DataFrame !


In [ ]:
dict = {
    "country":["Brazil", "Russia", "India", "China", "South Africa"],
    "capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
       "area":[8.516, 17.10, 3.286, 9.597, 1.221],
 "population":[200.4, 143.5, 1252, 1357, 52.98] }

In [ ]:
dict["country"]

['Brazil', 'Russia', 'India', 'China', 'South Africa']

In [ ]:
dict

{'country': ['Brazil', 'Russia', 'India', 'China', 'South Africa'],
 'capital': ['Brasilia', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
 'area': [8.516, 17.1, 3.286, 9.597, 1.221],
 'population': [200.4, 143.5, 1252, 1357, 52.98]}

In [ ]:
dict["country"][0]

'Brazil'

In [ ]:
dict["country"][0:3]

['Brazil', 'Russia', 'India']

In [ ]:
import pandas as pd

In [ ]:
brics = pd.DataFrame(dict)

In [ ]:
brics

country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [ ]:
brics.index = ["BR", "RU", "IN", "CH", "SA"]

In [ ]:
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
brics2 = pd.read_csv("/Users/marcosdeoliveira/brics.csv")

In [ ]:
brics2

Unnamed: 0       country    capital    area  population
0         BR        Brazil   Brasilia   8.516      200.40
1         RU        Russia     Moscow  17.100      143.50
2         IN         India  New Delhi   3.286     1252.00
3         CH         China    Beijing   9.597     1357.00
4         SA  South Africa   Pretoria   1.221       52.98

In [ ]:
brics2 = pd.read_csv("/Users/marcosdeoliveira/brics.csv", index_col = 0)

In [ ]:
brics2

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

# Seleção no pandas DataFrame

# Acesso a Colunas

In [ ]:
brics2["country"]

BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [ ]:
type(brics2["country"])

pandas.core.series.Series

In [ ]:
brics2[["country"]]

country
BR        Brazil
RU        Russia
IN         India
CH         China
SA  South Africa

In [ ]:
type(brics2[["country"]])

pandas.core.frame.DataFrame

In [ ]:
brics2[["country", "capital"]]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

# Acesso a linhas

In [ ]:
brics2[1:4]

country    capital    area  population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
brics2

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
type(brics2)

pandas.core.frame.DataFrame

In [ ]:
brics2.index

Index(['BR', 'RU', 'IN', 'CH', 'SA'], dtype='object')

In [ ]:
brics2.loc["RU"]

country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object

In [ ]:
brics2.loc[["RU"]]

country capital  area  population
RU  Russia  Moscow  17.1       143.5

In [ ]:
brics2.loc[["RU", "IN", "CH"]]

country    capital    area  population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
brics2.loc[["RU", "IN", "CH"], ["country", "capital"]]

country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [ ]:
brics2

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
brics2.loc[:, ["country", "capital"]]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

In [ ]:
brics2.iloc[[1]]

country capital  area  population
RU  Russia  Moscow  17.1       143.5

In [ ]:
brics2.iloc[[1,2,3]]

country    capital    area  population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
brics2.iloc[[1,2,3], [0, 1]]

country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [ ]:
brics2.iloc[:, [0,1]]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

# Seleção em Numpy Arrays

In [ ]:
altura = [1.73, 1.68, 1.71, 1.89, 1.79]

In [ ]:
peso = [65.4, 59.2, 63.6, 88.4, 68.7]

In [ ]:
import numpy as np

In [ ]:
a_altura = np.array(altura)
a_peso = np.array(peso)

In [ ]:
imc = a_peso / a_altura **2

In [ ]:
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
imc > 21

array([ True, False,  True,  True,  True])

In [ ]:
imc < 23

array([ True,  True,  True, False,  True])

In [ ]:
imc > 21 & imc < 23

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
np.logical_and(imc > 21, imc < 23)

In [ ]:
imc[np.logical_and(imc > 21, imc < 23)]

array([21.85171573, 21.75028214, 21.44127836])

In [ ]:
z = 3
if z % 2 == 0 :
    print("z é divisível por 2")
elif z % 3 == 0 :
    print("z é divisível por 3")
else :
    print("z não é divisível por 2 nem por 3")

z é divisível por 3


# Seleção em DataFrames

In [ ]:
brics2

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

- Selecionando os países com área maior que 8.000 kmˆ2

In [ ]:
brics2["area"]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
brics2["area"] > 8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
brics2[brics2["area"] > 8]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [ ]:
np.logical_and(brics2["area"] > 8, brics2["area"] < 10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
brics2[np.logical_and(brics2["area"] > 8, brics2["area"] < 10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

In [ ]:
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
for valor in imc :
    print(valor)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [ ]:
altura

[1.73, 1.68, 1.71, 1.89, 1.79]

In [ ]:
peso

[65.4, 59.2, 63.6, 88.4, 68.7]

In [ ]:
x = np.array([a_altura, a_peso])

In [ ]:
x

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [ ]:
for valor in x :
    print(valor)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [ ]:
for valor in np.nditer(x) :
    print(valor)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [ ]:
world

{'afghanistan': 30.55, 'albania': 2.81, 'algeria': 39.21}

In [ ]:
for chave, valor in world.items() :
    print(chave + " -- " + str(valor))

afghanistan -- 30.55
albania -- 2.81
algeria -- 39.21


In [ ]:
brics2

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
for valor in brics2 :
     print(valor)

country
capital
area
population


In [ ]:
for rotulo, linha in brics2.iterrows() :
    print(rotulo)
    print(linha)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population         1252
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population       1357
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


In [ ]:
brics2

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
for rotulo, linha in brics2.iterrows() :
     print(rotulo + ": " + linha["capital"])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


In [ ]:
 for rotulo, linha in brics2.iterrows() :
    brics2.loc[rotulo, "name_length"] = len(linha["country"])

In [ ]:
brics2

country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          5.0
CH         China    Beijing   9.597     1357.00          5.0
SA  South Africa   Pretoria   1.221       52.98         12.0

In [ ]:
del(brics2["name_length"])

In [ ]:
brics2

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
brics2["name_length"] = brics2["country"].apply(len)

In [ ]:
brics2

country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40            6
RU        Russia     Moscow  17.100      143.50            6
IN         India  New Delhi   3.286     1252.00            5
CH         China    Beijing   9.597     1357.00            5
SA  South Africa   Pretoria   1.221       52.98           12

In [ ]:
help(pd.read_json)

Help on function read_json in module pandas.io.json.json:

read_json(path_or_buf=None, orient=None, typ='frame', dtype=True, convert_axes=True, convert_dates=True, keep_default_dates=True, numpy=False, precise_float=False, date_unit=None, encoding=None, lines=False, chunksize=None, compression='infer')
    Convert a JSON string to pandas object
    
    Parameters
    ----------
    path_or_buf : a valid JSON string or file-like, default: None
        The string could be a URL. Valid URL schemes include http, ftp, s3, and
        file. For file URLs, a host is expected. For instance, a local file
        could be ``file://localhost/path/to/table.json``
    
    orient : string,
        Indication of expected JSON string format.
        Compatible JSON strings can be produced by ``to_json()`` with a
        corresponding orient value.
        The set of possible orients is:
    
        - ``'split'`` : dict like
          ``{index -> [index], columns -> [columns], data -> [values]}``
  

# Exercício

Como exercício o aluno deve seguir o tutorial disponível no link a seguir e enviar o notebook até Terça dia 19 pelo MOODLE:
[Primeiros passos com Pandas](https://medium.com/data-hackers/uma-introdução-simples-ao-pandas-1e15eea37fa1)